baseURL = "https://reinlearn.github.io"
languageCode = "en-us"
title = "reinlog"
theme = "charaka-hugo-theme"

[params]

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about.html"
  fa_icon = "fas fa-info" 

[[params.social]]
  url = "https://github.com/reinlearn"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://twitter.com/reinlearn"
  fa_icon = "fab fa-twitter"